name:  Application CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: epds-search
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
    - run: pip install -r requirements_dev.txt
    - run: cd ./app/ ; ./manage.py test
